In [1]:
pip install numpy


  Using cached numpy-2.2.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [4]:
x = [1, 2, 3, 4]
print(type(x))
v = np.array(x)
print(type(v))

<class 'list'>
<class 'numpy.ndarray'>


In [12]:
s = np.array(5)
print(s.ndim)
print(s.shape)
v = np.array([1, 2, 3, 4,5,6])
print(v.ndim)
print(v.shape)
print("===============================")
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m.ndim)
print(m.shape)

0
()
1
(6,)
2
(3, 3)


In [13]:
vec = np.array([1, 2, 3, 4, 5, 6])
mat =  vec.reshape(3, 2)
print(mat)

[[1 2]
 [3 4]
 [5 6]]


In [16]:
vec = np.array([1, 2, 3, 4])
mat = vec.reshape(vec.shape[0], 1)
print(mat)

[[1]
 [2]
 [3]
 [4]]


In [19]:
def array_reshape(arr:list, rows:int = -1, cols:int = -1)->np.ndarray:
    try:
        arr = np.array(arr)
        return arr.reshape(rows, cols)
    except (TypeError, ValueError) as e:
        raise ValueError(f"invalid reshape operation: {e}")    

In [22]:
vec = [1, 2, 3, 4, 5, 6]
mat = array_reshape(vec, 2, 3)
print(mat)

[[1 2 3]
 [4 5 6]]


In [24]:
m = np.array([[1.6, 2.1, 3], [4, 5, 6], [7, 8, 9]])

fmat = m.astype(int)
print(fmat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
